### ISSUE TITLE
Error starting etherpad

### ISSUE THREAD

**Issue by leon1995** [bigbluebutton/docker#102]
When starting, etherpad prints the following errors:
```
etherpad_1             | [2021-05-03 08:10:03.038] [INFO] server - Starting Etherpad...
etherpad_1             | [2021-05-03 08:10:03.050] [INFO] plugins - Running npm to get a list of installed plugins...
etherpad_1             | [2021-05-03 08:10:03.217] [INFO] plugins - npm --version: 6.14.11
etherpad_1             | [2021-05-03 08:10:04.893] [ERROR] runCmd|npm - npm ERR! error in /opt/etherpad-lite/node_modules/ep_bigbluebutton_patches: ENOENT: no such file or directory, open '/opt/etherpad-lite/node_modules/ep_bigbluebutton_patches/package.json'
etherpad_1             | [2021-05-03 08:10:04.901] [ERROR] server - Error occurred while starting Etherpad
etherpad_1             | [2021-05-03 08:10:04.903] [ERROR] server - Metrics at time of fatal error:
etherpad_1             | {
etherpad_1             |   "httpStartTime": 0,
etherpad_1             |   "memoryUsage": 69869568,
etherpad_1             |   "memoryUsageHeap": 12013384,
etherpad_1             |   "ueberdb_lockAwaits": 0,
etherpad_1             |   "ueberdb_lockAcquires": 0,
etherpad_1             |   "ueberdb_lockReleases": 0,
etherpad_1             |   "ueberdb_reads": 0,
etherpad_1             |   "ueberdb_readsFailed": 0,
etherpad_1             |   "ueberdb_readsFinished": 0,
etherpad_1             |   "ueberdb_readsFromCache": 0,
etherpad_1             |   "ueberdb_readsFromDb": 0,
etherpad_1             |   "ueberdb_readsFromDbFailed": 0,
etherpad_1             |   "ueberdb_readsFromDbFinished": 0,
etherpad_1             |   "ueberdb_writes": 0,
etherpad_1             |   "ueberdb_writesFailed": 0,
etherpad_1             |   "ueberdb_writesFinished": 0,
etherpad_1             |   "ueberdb_writesObsoleted": 0,
etherpad_1             |   "ueberdb_writesToDb": 0,
etherpad_1             |   "ueberdb_writesToDbFailed": 0,
etherpad_1             |   "ueberdb_writesToDbFinished": 0
etherpad_1             | }
etherpad_1             | [2021-05-03 08:10:04.903] [ERROR] server - Error: Command exited with code 1: npm ls --long --json --depth=0 --no-production
etherpad_1             |     at exports (/opt/etherpad-lite/src/node/utils/run_cmd.js:119:25)
etherpad_1             |     at Object.exports.getPackages (/opt/etherpad-lite/src/static/js/pluginfw/plugins.js:125:48)
etherpad_1             |     at Object.exports.update (/opt/etherpad-lite/src/static/js/pluginfw/plugins.js:99:34)
etherpad_1             |     at Object.exports.start (/opt/etherpad-lite/src/node/server.js:139:19)
etherpad_1             |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
etherpad_1             | [2021-05-03 08:10:04.903] [INFO] server - Exiting...
etherpad_1             | [2021-05-03 08:10:04.904] [INFO] server - Waiting for Node.js to exit...
etherpad_1             | [2021-05-03 08:13:43.458] [ERROR] server - Something that should have been cleaned up during the shutdown hook (such as a timer, worker thread, or open connection) is preventing Node.js from exiting
etherpad_1             | [2021-05-03 08:13:43.459] [INFO] console - [WTF Node?] open handles:
etherpad_1             | [2021-05-03 08:13:43.459] [INFO] console - - File descriptors: (note: stdio always exists)
etherpad_1             | [2021-05-03 08:13:43.460] [INFO] console -   - fd 1 (stdio)
etherpad_1             | [2021-05-03 08:13:43.460] [INFO] console -   - fd 2 (stdio)
etherpad_1             | [2021-05-03 08:13:43.461] [INFO] console - - Sockets:
etherpad_1             | [2021-05-03 08:13:43.462] [INFO] console -   - 10.7.7.4:34494 -> 10.7.7.5:6379
etherpad_1             | [2021-05-03 08:13:43.463] [INFO] console - - Intervals:
etherpad_1             | [2021-05-03 08:13:43.464] [INFO] console -   - (100 ~ 100 ms) (anonymous) @ /opt/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:225
etherpad_1             | [2021-05-03 08:13:43.464] [ERROR] server - Forcing an unclean exit...
bigbluebutton_etherpad_1 exited with code 1
```

**Comment by alangecker** [comment]
also submodules missing? :D

**Comment by leon1995** [comment]
I think not because I already executed `$ git submodule update --init`

**Comment by alangecker** [comment]
is there any content in the folder `mod/etherpad/bbb-etherpad-plugin`?
if yes, maybe try `$ docker-compose build --no-cache etherpad`

**Comment by leon1995** [comment]
rebuilding fixed it
