### ISSUE TITLE
recording do not save and publish... :(

### ISSUE THREAD

**Issue by farsad2020** [bigbluebutton/docker#160]
Hi 
Unfortunately from 2 Oct all recording with out any errors capture but donot publish when check them there is nothing and no process from them just in /bigbluebutton/recording/raw create directory and there is no file or data in it

```
Internal MeetingID                                      Time                        APVD APVDE     RAS             Slides                        Processed            Published           External MeetingID
------------------------------------------------------  ---------------------------- ---- ----- --- ------ -------------------- ------------------  -------------------
77d9722f0ea0e46dfbd932ee4720d8f8d187f781-1633767933464  Sat 09 Oct 2021 08:25:33 AM UTC  X                  1
d5fecc48b8b2952586b0248f1a330e24349c660a-1633363146121  Mon 04 Oct 2021 03:59:06 PM UTC  X                  0
d5fecc48b8b2952586b0248f1a330e24349c660a-1633362727196  Mon 04 Oct 2021 03:52:07 PM UTC  X                  0
cedfa2a8af5dfbb29eafd0a0994257b403b74ac5-1633344476909  Mon 04 Oct 2021 10:47:56 AM UTC  X                 15
cedfa2a8af5dfbb29eafd0a0994257b403b74ac5-1633344069638  Mon 04 Oct 2021 10:41:09 AM UTC  X                 15
244dbb64501c02ad7767d3a4c417f7f615e47c37-1633343867656  Mon 04 Oct 2021 10:37:47 AM UTC  X                  1
cedfa2a8af5dfbb29eafd0a0994257b403b74ac5-1633341936377  Mon 04 Oct 2021 10:05:36 AM UTC  X                 15
4213bdd8acb395d17386ee3ed458e62b25e59402-1633341437408  Mon 04 Oct 2021 09:57:17 AM UTC  X                  1
3988030ab208820711f5cd7064819d756793e572-1633341292447  Mon 04 Oct 2021 09:54:52 AM UTC  X                  1
244dbb64501c02ad7767d3a4c417f7f615e47c37-1633339886299  Mon 04 Oct 2021 09:31:26 AM UTC  X                  1
244dbb64501c02ad7767d3a4c417f7f615e47c37-1633338674826  Mon 04 Oct 2021 09:11:14 AM UTC  X                  1
cedfa2a8af5dfbb29eafd0a0994257b403b74ac5-1633338199994  Mon 04 Oct 2021 09:03:19 AM UTC  X                 15
2c356fd6371f0ec47fc2a0da95113bfae1291fcb-1633338189689  Mon 04 Oct 2021 09:03:09 AM UTC  X                 15
244dbb64501c02ad7767d3a4c417f7f615e47c37-1633278789224  Sun 03 Oct 2021 04:33:09 PM UTC  X                  1
4213bdd8acb395d17386ee3ed458e62b25e59402-1633261188077  Sun 03 Oct 2021 11:39:48 AM UTC  X                  1
d5fecc48b8b2952586b0248f1a330e24349c660a-1633256789107  Sun 03 Oct 2021 10:26:29 AM UTC  X                 61
d5fecc48b8b2952586b0248f1a330e24349c660a-1633254706464  Sun 03 Oct 2021 09:51:46 AM UTC  X                 61
3988030ab208820711f5cd7064819d756793e572-1633250265282  Sun 03 Oct 2021 08:37:45 AM UTC  X                  1
d5fecc48b8b2952586b0248f1a330e24349c660a-1633240569844  Sun 03 Oct 2021 05:56:09 AM UTC  X                  0
4213bdd8acb395d17386ee3ed458e62b25e59402-1633237089234  Sun 03 Oct 2021 04:58:09 AM UTC  X                  1
```

**Comment by farsad2020** [comment]
Hi
 I sync all bigbluebutton directory to free server with bigbluebutton that is as service on os  and rebuild theme now 2 of theme came back and published :D realy nice...

**Comment by farsad2020** [comment]
logs are like that and repeated 

recordings_1           | ** [06:36:30 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:36:35 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:36:35 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:36:35 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:36:35 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:36:35 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:36:35 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:36:35 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:36:40 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:36:40 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:36:40 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:36:40 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:36:40 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:36:40 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:36:40 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:36:45 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:36:45 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:36:45 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:36:45 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:36:45 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:36:45 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:36:45 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:36:50 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:36:50 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:36:50 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:36:50 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:36:50 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:36:50 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:36:50 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:36:55 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:36:55 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:36:55 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:36:55 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:36:55 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:36:55 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:36:55 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:37:00 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:37:00 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:37:00 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:37:00 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:37:00 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:37:00 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:37:00 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:37:05 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:37:05 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:37:05 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:37:05 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:37:05 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:37:05 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:37:05 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:37:10 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:37:10 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:37:10 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:37:10 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:37:10 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:37:10 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:37:10 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:37:15 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:37:15 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:37:15 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:37:15 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:37:15 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:37:15 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:37:15 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:37:20 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:37:20 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:37:20 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:37:20 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:37:20 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:37:20 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:37:20 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:37:25 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:37:25 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:37:25 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:37:25 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:37:25 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:37:25 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:37:25 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:37:30 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:37:30 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:37:30 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:37:30 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:37:30 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:37:30 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:37:30 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:37:35 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:37:35 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:37:35 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:37:35 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:37:35 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:37:35 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:37:35 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:37:40 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:37:40 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:37:40 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:37:40 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:37:40 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:37:40 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:37:40 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:37:45 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:37:45 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:37:45 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:37:45 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:37:45 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:37:45 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:37:45 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:37:50 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:37:50 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:37:50 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:37:50 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:37:50 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:37:50 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:37:50 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:37:55 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:37:55 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:37:55 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:37:55 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:37:55 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:37:55 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:37:55 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:38:00 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:38:00 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:38:00 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:38:00 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:38:00 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:38:00 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:38:00 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:38:05 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:38:05 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:38:05 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:38:05 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:38:05 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:38:05 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:38:05 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:38:10 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:38:10 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:38:10 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:38:10 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:38:10 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:38:10 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:38:10 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:38:15 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:38:15 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:38:15 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:38:15 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:38:15 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:38:15 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:38:15 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
recordings_1           | ** [06:38:20 2021-10-02] 31: Checking rap:archive
recordings_1           | ** [06:38:20 2021-10-02] 31: Checking rap:publish
recordings_1           | ** [06:38:20 2021-10-02] 31: Checking rap:process
recordings_1           | ** [06:38:20 2021-10-02] 31: Checking rap:sanity
recordings_1           | ** [06:38:20 2021-10-02] 31: Checking rap:captions
recordings_1           | ** [06:38:20 2021-10-02] 31: Sleeping for 5.0 seconds
recordings_1           | ** [06:38:20 2021-10-02] 31: resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions

**Comment by farsad2020** [comment]
if grep on ERROR

recordings_1           | E, [2021-10-04T10:36:24.744363 #186] ERROR -- : Error connecting to Redis on redis:6379 (Errno::ECONNREFUSED)
recordings_1           | E, [2021-10-04T10:36:24.744805 #186] ERROR -- : /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:362:in `rescue in establish_connection'
recordings_1           | E, [2021-10-04T10:36:24.745074 #186] ERROR -- : /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:343:in `establish_connection'
recordings_1           | E, [2021-10-04T10:36:24.745349 #186] ERROR -- : /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:106:in `block in connect'
recordings_1           | E, [2021-10-04T10:36:24.745854 #186] ERROR -- : /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:306:in `with_reconnect'
recordings_1           | E, [2021-10-04T10:36:24.746070 #186] ERROR -- : /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:105:in `connect'
recordings_1           | E, [2021-10-04T10:36:24.746258 #186] ERROR -- : /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:381:in `ensure_connected'
recordings_1           | E, [2021-10-04T10:36:24.746578 #186] ERROR -- : /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:231:in `block in process'
recordings_1           | E, [2021-10-04T10:36:24.746850 #186] ERROR -- : /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:319:in `logging'
recordings_1           | E, [2021-10-04T10:36:24.747036 #186] ERROR -- : /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:230:in `process'
recordings_1           | E, [2021-10-04T10:36:24.747596 #186] ERROR -- : /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:125:in `call'
recordings_1           | E, [2021-10-04T10:36:24.747707 #186] ERROR -- : /usr/local/bundle/gems/redis-4.1.3/lib/redis.rb:2287:in `block in publish'
recordings_1           | E, [2021-10-04T10:36:24.750716 #186] ERROR -- : /usr/local/bundle/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
recordings_1           | E, [2021-10-04T10:36:24.750860 #186] ERROR -- : /usr/local/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
recordings_1           | E, [2021-10-04T10:36:24.750928 #186] ERROR -- : /usr/local/bundle/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
recordings_1           | E, [2021-10-04T10:36:24.750986 #186] ERROR -- : /usr/local/bundle/gems/redis-4.1.3/lib/redis.rb:2286:in `publish'
recordings_1           | E, [2021-10-04T10:36:24.751041 #186] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:153:in `put_message'
recordings_1           | E, [2021-10-04T10:36:24.751105 #186] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:176:in `put_archive_ended'
recordings_1           | E, [2021-10-04T10:36:24.751164 #186] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/workers/archive_worker.rb:48:in `block in perform'
recordings_1           | E, [2021-10-04T10:36:24.751219 #186] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/workers/base_worker.rb:53:in `perform'
recordings_1           | E, [2021-10-04T10:36:24.751274 #186] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/workers/archive_worker.rb:26:in `perform'
recordings_1           | E, [2021-10-04T10:36:24.751341 #186] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/workers/base_worker.rb:44:in `perform'
recordings_1           | E, [2021-10-04T10:36:24.751409 #186] ERROR -- : /usr/local/bundle/gems/resque-2.0.0/lib/resque/job.rb:168:in `perform'
recordings_1           | E, [2021-10-04T10:36:24.751508 #186] ERROR -- : /usr/local/bundle/gems/resque-2.0.0/lib/resque/worker.rb:308:in `perform'
recordings_1           | E, [2021-10-04T10:36:24.751586 #186] ERROR -- : /usr/local/bundle/gems/resque-2.0.0/lib/resque/worker.rb:897:in `block in perform_with_fork'
recordings_1           | E, [2021-10-04T10:36:24.751645 #186] ERROR -- : /usr/local/bundle/gems/resque-2.0.0/lib/resque/worker.rb:895:in `fork'
recordings_1           | E, [2021-10-04T10:36:24.751712 #186] ERROR -- : /usr/local/bundle/gems/resque-2.0.0/lib/resque/worker.rb:895:in `perform_with_fork'
recordings_1           | E, [2021-10-04T10:36:24.751770 #186] ERROR -- : /usr/local/bundle/gems/resque-2.0.0/lib/resque/worker.rb:264:in `work_one_job'
recordings_1           | E, [2021-10-04T10:36:24.751826 #186] ERROR -- : /usr/local/bundle/gems/resque-2.0.0/lib/resque/worker.rb:238:in `block in work'
recordings_1           | E, [2021-10-04T10:36:24.751881 #186] ERROR -- : /usr/local/bundle/gems/resque-2.0.0/lib/resque/worker.rb:235:in `loop'
recordings_1           | E, [2021-10-04T10:36:24.751937 #186] ERROR -- : /usr/local/bundle/gems/resque-2.0.0/lib/resque/worker.rb:235:in `work'
recordings_1           | E, [2021-10-04T10:36:24.752625 #186] ERROR -- : /usr/local/bundle/gems/resque-2.0.0/lib/resque/tasks.rb:20:in `block (2 levels) in <top (required)>'
recordings_1           | E, [2021-10-04T10:36:24.753214 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
recordings_1           | E, [2021-10-04T10:36:24.753430 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
recordings_1           | E, [2021-10-04T10:36:24.753928 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
recordings_1           | E, [2021-10-04T10:36:24.754208 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
recordings_1           | E, [2021-10-04T10:36:24.754400 #186] ERROR -- : /usr/local/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
recordings_1           | E, [2021-10-04T10:36:24.754725 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
recordings_1           | E, [2021-10-04T10:36:24.754923 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
recordings_1           | E, [2021-10-04T10:36:24.755110 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
recordings_1           | E, [2021-10-04T10:36:24.755438 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
recordings_1           | E, [2021-10-04T10:36:24.755673 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'
recordings_1           | E, [2021-10-04T10:36:24.755996 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
recordings_1           | E, [2021-10-04T10:36:24.756276 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
recordings_1           | E, [2021-10-04T10:36:24.756603 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
recordings_1           | E, [2021-10-04T10:36:24.756915 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
recordings_1           | E, [2021-10-04T10:36:24.757147 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
recordings_1           | E, [2021-10-04T10:36:24.757562 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
recordings_1           | E, [2021-10-04T10:36:24.757888 #186] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
recordings_1           | E, [2021-10-04T10:36:24.758121 #186] ERROR -- : /usr/local/bin/rake:23:in `load'
recordings_1           | E, [2021-10-04T10:36:24.758582 #186] ERROR -- : /usr/local/bin/rake:23:in `<main>'
recordings_1           | E, [2021-10-04T10:36:24.759312 #186] ERROR -- : (Job{rap:archive} | BigBlueButton::Resque::ArchiveWorker | [{"meeting_id"=>"4213bdd8acb395d17386ee3ed458e62b25e59402-1633179845315", "break_timestamp"=>nil}]) failed: #<Redis::CannotConnectError: Error connecting to Redis on redis:6379 (Errno::ECONNREFUSED)>
recordings_1           | E, [2021-10-04T10:36:24.768810 #186] ERROR -- : Received exception when reporting failure: #<Redis::CannotConnectError: Error connecting to Redis on redis:6379 (Errno::ECONNREFUSED)>
recordings_1           | E, [2021-10-04T10:36:24.772210 #186] ERROR -- : Received exception when increasing failed jobs counter (redis issue) : #<Redis::CannotConnectError: Error connecting to Redis on redis:6379 (Errno::ECONNREFUSED)>



but date of them are for 2 days after recorded

**Comment by alangecker** [comment]
sorry, I did a mistake, recording works fine for me:
```
$ ./scripts/bbb-record --list  
Internal MeetingID                                               Time                APVD APVDE RAS Slides Processed            Published           External MeetingID
------------------------------------------------------  ---------------------------- ---- ----- --- ------ -------------------- ------------------  -------------------
0323338e6956ef2eeded39b685d0b8d97dd5a490-1633861646993  Sun 10 Oct 2021 10:27:26 AM UTC  X   XXX X  XX     15 presentation         presentation        random-4575569
cb55040b673a6a0c0556c528a59d4f35433a2678-1633859813271  Sun 10 Oct 2021 09:56:53 AM UTC  X   XXX X         15                                          random-5026527
62aa1401da4c46c1a5768587b7b878016d3b5e15-1633859797952  Sun 10 Oct 2021 09:56:37 AM UTC  X                 15 

your logs show `Error connecting to Redis on redis:6379`. is redis running?
you can check that with `docker-compose ps`

**Comment by farsad2020** [comment]
yes this container was up and healthy 
but for make sure docker-compose restart 


             Name                            Command                  State                Ports
-----------------------------------------------------------------------------------------------------------
bbb-docker_apps-akka_1             /bin/sh -c dockerize     - ...   Up
bbb-docker_bbb-web_1               /entrypoint.sh                   Up (healthy)
bbb-docker_etherpad_1              /entrypoint.sh                   Up             9001/tcp
bbb-docker_freeswitch_1            /bin/sh -c /entrypoint.sh        Up
bbb-docker_fsesl-akka_1            /bin/sh -c dockerize     - ...   Up
bbb-docker_greenlight_1            bin/start                        Up             10.7.7.1:5010->80/tcp
bbb-docker_html5-backend-1_1       /entrypoint.sh                   Up
bbb-docker_html5-frontend-1_1      /entrypoint.sh                   Up
bbb-docker_jodconverter_1          /docker-entrypoint.sh --sp ...   Up
bbb-docker_kurento_1               /entrypoint.sh                   Up (healthy)
bbb-docker_mongodb_1               docker-entrypoint.sh mongo ...   Up (healthy)   27017/tcp
bbb-docker_nginx_1                 /docker-entrypoint.sh ngin ...   Up
bbb-docker_periodic_1              /entrypoint.sh                   Up
bbb-docker_postgres_1              docker-entrypoint.sh postgres    Up (healthy)   5432/tcp
bbb-docker_prometheus-exporter_1   python server.py                 Up             9688/tcp
bbb-docker_recordings_1            /bin/sh -c /entrypoint.sh        Up
bbb-docker_redis_1                 docker-entrypoint.sh redis ...   Up (healthy)   6379/tcp
bbb-docker_webrtc-sfu_1            ./docker-entrypoint.sh npm ...   Up             127.0.0.1:3008->3008/tcp

**Comment by moacirbmn** [comment]
I have the same problem, I still haven't found a definitive solution

Looks like they already found the problem [here,](https://github.com/bigbluebutton/bigbluebutton/issues/15179) but I don't know how to solve it

**Comment by alangecker** [comment]
would be great if you could retry it with the current `develop` branch

```bash
git checkout develop
./scripts/upgrade
```

when doing the update, be aware about the breaking changes with greenlight:
https://github.com/bigbluebutton/docker/blob/develop/docs/upgrading.md
