### ISSUE TITLE
Steps to work behind NAT

### ISSUE THREAD

**Issue by qubex22** [bigbluebutton/docker#222]
The workaround in this doc https://github.com/bigbluebutton/docker/blob/develop/docs/behind-nat.md is outdated or doesn't work.

What I've done to make it work:

1. The variable EXTERNAL_IPv4 in .env should be the private ip of the host. If you put the public ip and port forward in your router when the packets reach bbb they would be searching for your publicIp:port and finally the result would be port unreachable. (the workaround that adds the public ip to the loopback doesn't  fully work if you port forward and NAT)

2. Now freeswitch and mediasoup bind to the private ip, because we have port forwarded every needed udp port  16384-32768 there is no problem. The problem now is that Mediasoup have an "announcedIp" variable that sould ALWAYS be the public ip, if not, webrtc won't work

3. To change this, we should edit the docker-compose.yml at these lines:
`      
MS_WEBRTC_LISTEN_IPS: '[{"ip":"${EXTERNAL_IPv4}", "announcedIp":"x.x.x.x"}]'
MS_RTP_LISTEN_IP: '{"ip":"0.0.0.0", "announcedIp":"x.x.x.x"}'
`
where x.x.x.x is your public ip

I think in next releases this could be sorted out having both variables in the .env file like INTERNAL_IPv4 and EXTERNAL_IPv4 only when the setup is behind NAT

Hope this helps :vulcan_salute:

**Comment by YounessKazzoul** [comment]
@qubex22 Thank you so so much, it works fine for me 👍

**Comment by YounessKazzoul** [comment]
@qubex22  at step 6/15 I had a block, and I had this exit and then it continued normal as if no problem! do you have an idea of the problem, please?


Step 4/15 : USER etherpad
 ---> Running in d9f44340a774
Removing intermediate container d9f44340a774
 ---> cac183cc112b
Step 5/15 : RUN npm install      ep_cursortrace@3.1.16     git+https://github.com/mconf/ep_pad_ttl.git#360136cd38493dd698435631f2373cbb7089082d     git+https://github.com/mconf/ep_redis_publisher.git#a30a48e4bc1e501b5b102884b9a0b26c30798484     ep_disable_chat@0.0.8     ep_auth_session@1.1.1     && rm package-lock.json
 ---> Running in 6827006e8803
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> sqlite3@5.0.2 install /opt/etherpad-lite/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install request to https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-x64.tar.gz failed, reason: getaddrinfo ENOTFOUND mapbox-node-binary.s3.amazonaws.com
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.0.2 and node@14.19.1 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error request to https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-x64.tar.gz failed, reason: getaddrinfo ENOTFOUND mapbox-node-binary.s3.amazonaws.com
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:402:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
gyp ERR! System Linux 3.10.0-1160.76.1.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/etherpad-lite/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/opt/etherpad-lite/node_modules/sqlite3/lib/binding/napi-v3-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /opt/etherpad-lite/node_modules/sqlite3
gyp ERR! node -v v14.19.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/etherpad-lite/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/opt/etherpad-lite/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/etherpad-lite/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
node-pre-gyp ERR! System Linux 3.10.0-1160.76.1.el7.x86_64
node-pre-gyp ERR! command "/usr/local/bin/node" "/opt/etherpad-lite/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/etherpad-lite/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.19.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/etherpad-lite/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/opt/etherpad-lite/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm WARN saveError ENOENT: no such file or directory, open '/opt/etherpad-lite/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/opt/etherpad-lite/package.json'
npm WARN etherpad-lite No description
npm WARN etherpad-lite No repository field.
npm WARN etherpad-lite No README data
npm WARN etherpad-lite No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@5.0.2 (node_modules/sqlite3):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@5.0.2 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ ep_pad_ttl@1.0.0
+ ep_redis_publisher@0.0.3
+ ep_disable_chat@0.0.8
+ ep_cursortrace@3.1.16
+ ep_auth_session@1.1.1
added 13 packages from 14 contributors and audited 1053 packages in 829.678s

59 packages are looking for funding
  run `npm fund` for details

found 44 vulnerabilities (3 moderate, 23 high, 18 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container 6827006e8803
 ---> 2c12b7284391
Step 6/15 : COPY --chown=etherpad:0 ./bbb-etherpad-skin /opt/etherpad-lite/src/static/skins/bigbluebutton
 ---> 9568f5f42824
