### ISSUE TITLE
502 bad gateway while joining room

### ISSUE THREAD

**Issue by Hiajen** [bigbluebutton/docker#224]
Hay there,

Problem:
When joining a Room, the User lands on an 502 Error page of the internal nginx server.
Greenlight Frontend works fine `/bigbluebutton/api` is reachable returning success but joining a room is not possible.

Setup:
- greenlight y
- https proxy n
- cotrun n
- domain xxx
- recording n
- promethius y
- importing old database

Startup spams following error:
```
bbb-mongodb                       | 
bbb-mongodb                       | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
bbb-mongodb                       |   see https://jira.mongodb.org/browse/SERVER-54407
bbb-mongodb                       |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
bbb-mongodb                       |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
bbb-mongodb                       | 
bbb-mongodb                       | error: unexpected "js-yaml.js" output while parsing config:
bbb-mongodb exited with code 1
[...]
bbb-docker-html5-frontend-2-1     | /app/programs/server/node_modules/fibers/future.js:313
bbb-docker-html5-frontend-2-1     | 						throw(ex);
bbb-docker-html5-frontend-2-1     | 						^
bbb-docker-html5-frontend-2-1     | 
bbb-docker-html5-frontend-2-1     | MongoServerSelectionError: connect EHOSTUNREACH 10.7.7.6:27017
bbb-docker-html5-frontend-2-1     |     at Timeout._onTimeout (/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:312:38)
bbb-docker-html5-frontend-2-1     |     at listOnTimeout (internal/timers.js:557:17)
bbb-docker-html5-frontend-2-1     |     at processTimers (internal/timers.js:500:7) {
bbb-docker-html5-frontend-2-1     |   reason: TopologyDescription {
bbb-docker-html5-frontend-2-1     |     type: 'Unknown',
bbb-docker-html5-frontend-2-1     |     servers: Map(1) {
bbb-docker-html5-frontend-2-1     |       '10.7.7.6:27017' => ServerDescription {
bbb-docker-html5-frontend-2-1     |         _hostAddress: HostAddress { isIPv6: false, host: '10.7.7.6', port: 27017 },
bbb-docker-html5-frontend-2-1     |         address: '10.7.7.6:27017',
bbb-docker-html5-frontend-2-1     |         type: 'Unknown',
bbb-docker-html5-frontend-2-1     |         hosts: [],
bbb-docker-html5-frontend-2-1     |         passives: [],
bbb-docker-html5-frontend-2-1     |         arbiters: [],
bbb-docker-html5-frontend-2-1     |         tags: {},
bbb-docker-html5-frontend-2-1     |         minWireVersion: 0,
bbb-docker-html5-frontend-2-1     |         maxWireVersion: 0,
bbb-docker-html5-frontend-2-1     |         roundTripTime: -1,
bbb-docker-html5-frontend-2-1     |         lastUpdateTime: 56601490,
bbb-docker-html5-frontend-2-1     |         lastWriteDate: 0,
bbb-docker-html5-frontend-2-1     |         error: MongoNetworkError: connect EHOSTUNREACH 10.7.7.6:27017
bbb-docker-html5-frontend-2-1     |             at connectionFailureError (/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:381:20)
bbb-docker-html5-frontend-2-1     |             at Socket.<anonymous> (/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:301:22)
bbb-docker-html5-frontend-2-1     |             at Object.onceWrapper (events.js:520:26)
bbb-docker-html5-frontend-2-1     |             at Socket.emit (events.js:400:28)
bbb-docker-html5-frontend-2-1     |             at Socket.emit (domain.js:475:12)
bbb-docker-html5-frontend-2-1     |             at emitErrorNT (internal/streams/destroy.js:106:8)
bbb-docker-html5-frontend-2-1     |             at emitErrorCloseNT (internal/streams/destroy.js:74:3)
bbb-docker-html5-frontend-2-1     |             at processTicksAndRejections (internal/process/task_queues.js:82:21)
bbb-docker-html5-frontend-2-1     |       }
bbb-docker-html5-frontend-2-1     |     },
bbb-docker-html5-frontend-2-1     |     stale: false,
bbb-docker-html5-frontend-2-1     |     compatible: true,
bbb-docker-html5-frontend-2-1     |     heartbeatFrequencyMS: 10000,
bbb-docker-html5-frontend-2-1     |     localThresholdMS: 15,
bbb-docker-html5-frontend-2-1     |     logicalSessionTimeoutMinutes: undefined
bbb-docker-html5-frontend-2-1     |   }
bbb-docker-html5-frontend-2-1     | }
bbb-docker-html5-frontend-2-1     | 2022/07/07 10:24:30 Command exited with error: exit status 1
[...]
bbb-docker-html5-backend-1-1      | 2022/07/07 10:26:10 Command exited with error: exit status 1
bbb-docker-html5-frontend-4-1 exited with code 1
bbb-docker-html5-backend-1-1 exited with code 1
```

How to solve this issue? Is it a config error on my side or a general issue?
Thanks i advance!

**Comment by Hiajen** [comment]
Pardon me, log says it all!

(Downgrading MongoDB image to version 4.4.15 solved my issue)
