### ISSUE TITLE
Fresh installation 2.5.8 Echec 1004 ICE error

### ISSUE THREAD

**Issue by mathben** [bigbluebutton/docker#250]
- Fresh installation Ubuntu Server 20.04.5
- Port forwading in router 80, 443, 16384-32768
- Install docker
```
git clone --recurse-submodules https://github.com/bigbluebutton/docker.git bbb-docker
cd bbb-docker
git checkout main 
./scripts/setup
```
// commit ab63e10e9243db14aba072a1fdbe8c53e7e49144 BBB 2.5.8

```
Should greenlight be included? (y/n): y
Should an automatic HTTPS Proxy be included? (y/n): y
Should a coturn be included? (y/n): n
Please enter the domain name: bbb.domainname.com
Should the recording feature be included?
   IMPORTANT: this is currently a big privacy issues, because it will 
   record everything which happens in the conference, even when the button
   suggests, that it does not.
   make sure that you always get people's consent, before they join a room!
   https://github.com/bigbluebutton/bigbluebutton/issues/9202
Choice (y/n): y
Should a Prometheus exporter be included? (y/n): n
Should old recordings be removed? (y/n): y
Please enter max age(days) for keeping recordings: 365
Is ###.###.###.### your external IPv4 address? (y/n): y
```

```
sudo docker-compose up -d

docker-compose exec greenlight bundle exec rake admin:create
```

Connect to Greenlight, start a room and the streaming not work with error
Echec 1004 ICE error
Erreur 2200 multimédia

**Comment by mathben** [comment]
From : docker-compose logs -f
```
switch_core_media.c:9795 AUDIO RTP REPORTS ERROR: [Bind Error!
```

**Comment by mathben** [comment]
After webcam open

bbb-docker4-webrtc-sfu-1        | {"errorStack":"Error: port bind failed due to address not available [transport:udp, ip:'###.###.###.###', port:27006, attempt:1/8192] [method:router.createWebRtcTransport]\n    at Channel.processMessage (/app/node_modules/mediasoup/node/lib/Channel.js:195:37)\n    at Socket.<anonymous> (/app/node_modules/mediasoup/node/lib/Channel.js:69:34)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)","label":"core","level":"error","message":"mediasoup: Stack trace for error 2019 | MEDIA_SERVER_GENERIC_ERROR ->","timestamp":"2023-02-03T00:11:07.972Z"}
bbb-docker4-webrtc-sfu-1        | {"error":{"code":2019,"details":"port bind failed due to address not available [transport:udp, ip:'###.###.###.###', port:27006, attempt:1/8192] [method:router.createWebRtcTransport]","message":"MEDIA_SERVER_GENERIC_ERROR","stack":"Error: port bind failed due to address not available [transport:udp, ip:'###.###.###.###', port:27006, attempt:1/8192] [method:router.createWebRtcTransport]\n    at Channel.processMessage (/app/node_modules/mediasoup/node/lib/Channel.js:195:37)\n    at Socket.<anonymous> (/app/node_modules/mediasoup/node/lib/Channel.js:69:34)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)","stackWasLogged":true},"label":"core","level":"error","mediaSessionId":"3f444bed-8689-412d-824f-bc770592819f","message":"SDP session: failed to process SDP session 3f444bed-8689-412d-824f-bc770592819f due to MEDIA_SERVER_GENERIC_ERROR","roomId":"30800","timestamp":"2023-02-03T00:11:07.973Z","userId":"50bd0037-4329-4ea9-97b4-c3a0f3271ee8"}
bbb-docker4-webrtc-sfu-1        | {"error":{"code":2019,"details":"port bind failed due to address not available [transport:udp, ip:'###.###.###.###', port:27006, attempt:1/8192] [method:router.createWebRtcTransport]","message":"MEDIA_SERVER_GENERIC_ERROR","stack":"Error: port bind failed due to address not available [transport:udp, ip:'###.###.###.###', port:27006, attempt:1/8192] [method:router.createWebRtcTransport]\n    at Channel.processMessage (/app/node_modules/mediasoup/node/lib/Channel.js:195:37)\n    at Socket.<anonymous> (/app/node_modules/mediasoup/node/lib/Channel.js:69:34)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)","stackWasLogged":true},"label":"core","level":"info","mediaSessionId":"3f444bed-8689-412d-824f-bc770592819f","message":"User: media session 3f444bed-8689-412d-824f-bc770592819f stopped and rolled back due to MEDIA_SERVER_GENERIC_ERROR","roomId":"30800","timestamp":"2023-02-03T00:11:07.974Z","userId":"50bd0037-4329-4ea9-97b4-c3a0f3271ee8"}

**Comment by mathben** [comment]
I installed BBB from https://github.com/bigbluebutton/bbb-install and the streaming work without error. Something is wrong in the docker-compose.

**Comment by mlutfy** [comment]
For what it's worth, I had a similar conflict because I had started with the traditional `bbb-install` setup, gave up and tried the docker install.

However, from my earlier tests I had coturn installed on the host server, and forgot to purge it.

Once purged, everything worked fine.

I used the default `develop` branch, did not test main.
